// Auto-generated by scripts/design/extract-card-system-v2-inventory.ts
// Do not edit manually.

import inventoryJson from "./card-system-v2.inventory.json";

export type InventoryEntry = {
  sectionId: string;
  sectionLabel: string;
  familyLabel: string;
  family: string;
  variantLabel: string;
  variant: string;
  key: `${string}.${string}`;
};

export type InventoryFile = {
  generatedAt: string;
  source: string;
  totalEntries: number;
  entries: InventoryEntry[];
};

export const cardSystemV2Inventory = inventoryJson as InventoryFile;
export const cardSystemV2CardKeys = [
  "budget-item.compact",
  "budget-item.planned",
  "budget-item.standard",
  "budget-summary.compact-summary",
  "budget-summary.full-summary",
  "budget-summary.income-item",
  "checklist.compact",
  "checklist.standard",
  "compact-cards.standard",
  "compare.compact",
  "compare.grid-4",
  "compare.side-by-side",
  "compare.slider",
  "contact.compact",
  "contact.standard",
  "contact.vendor-store",
  "container.character",
  "container.moodboard-link",
  "container.prop",
  "container.standard",
  "equipment.camera",
  "equipment.lens",
  "equipment.lighting",
  "event.compact",
  "event.photoshoot",
  "event.standard",
  "fabric.compact",
  "fabric.standard",
  "filament.flexible",
  "filament.standard",
  "foam.standard",
  "hardware.fasteners",
  "hardware.magnets",
  "hardware.structural",
  "image.landscape",
  "image.portrait",
  "image.square",
  "image.thumbnail",
  "instagram.carousel",
  "instagram.compact",
  "instagram.post",
  "instagram.reel",
  "leather.faux-leather",
  "leather.standard",
  "link.compact",
  "link.with-preview",
  "link.without-preview",
  "location.compact",
  "location.standard",
  "measurements.body",
  "measurements.compact",
  "measurements.garment",
  "metal.standard",
  "metal.wire",
  "moodboard-link.standard",
  "note.compact",
  "note.long-note",
  "note.standard",
  "palette.compact",
  "palette.horizontal-strip",
  "palette.standard",
  "piles.collapsed",
  "piles.expanded",
  "project-reference.standard",
  "resin.standard",
  "resin.uv-resin",
  "resource-reference.standard",
  "sketch.compact",
  "sketch.standard-sketch",
  "sketch.with-side-notes",
  "thermoplastic.compact",
  "thermoplastic.standard",
  "tiktok.compact",
  "tiktok.standard",
  "tools.compact",
  "tools.need-to-buy",
  "tools.owned",
  "wood.dowels",
  "wood.standard",
  "youtube.compact",
  "youtube.short",
  "youtube.video",
] as const;
export type CardSystemV2CardKey = (typeof cardSystemV2CardKeys)[number];
