name: E2E Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    environment: cosplans-test
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run E2E smoke tests
        run: bunx playwright test -g "smoke"
        env:
          CI: true
          SUPABASE_TEST_URL: ${{ secrets.SUPABASE_TEST_URL }}
          SUPABASE_TEST_KEY: ${{ secrets.SUPABASE_TEST_KEY }}
          TEST_BASE_URL: http://localhost:5173
          PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_TEST_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_TEST_KEY }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload flaky test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flaky-tests
          path: test-results/flaky-tests.*
          retention-days: 30

